### PR TITLE
Add Scala 2.13 compilation target

### PR DESCRIPTION
**Pull request by alonsodomin**

### CODE REVIEW

**Comment by alonsodomin** [comment]
Re-opening after wrong automatic merge happening in #141

**Comment by pjfanning** [comment]
@alonsodomin would it be possible to use cats-core 2.0.0-M3 for scala 2.13.0 compile?

**Comment by alonsodomin** [comment]
@pjfanning yeah, of course, it will need to be versioned as a milestone too though.

However, this is blocked on a release of contextual; not sure if it was already released or not...

**Comment by alonsodomin** [comment]
Once the build passes, this closes #187

**Comment by alonsodomin** [comment]
Finally got a successful build in Scala 2.12, the Scala 2.13 build is failing due to a macro expansion error in the `cron` macro powered by contextual

**Pull request merged**
